### ISSUE TITLE
Bug Report - "microlink.h" No such file or directory

### ISSUE THREAD

**Issue by TimDowker** [Csontikka/esphome-tailscale#28]
New issue with Esphome 2026.7

Getting this error now

"In file included from ../src/esphome/components/tailscale/tailscale.cpp:1:
../src/esphome/components/tailscale/tailscale.h:27:10: fatal error: microlink.h: No such file or directory
   27 | #include "microlink.h"
      |          ^~~~~~~~~~~~~
compilation terminated."

Previous versions worked fine - currently running Esphome 2026.6.4 and esphome 2026.6.5.

I've tried clearing the build files as well as resetting the build environment inside esphome and both fail to compile.  Other esphome devices are working as expected however they are local devices.

**Comment by Csontikka** [comment]
Confirmed, thanks for the report — this is an **ESPHome 2026.7 build-system change**, not a problem with your config. 2026.6.x builds fine; 2026.7 changed how it generates the ESP-IDF build, and the component's mechanism for wiring in the vendored `microlink` library (an `extra_scripts` pre-script that injects `EXTRA_COMPONENT_DIRS`, plus `-I` include flags) no longer takes effect there — so `#include "microlink.h"` can't be found.

**Workaround for right now:** pin ESPHome to **2026.6.x** (2026.6.5 is verified working — it's what the latest release is built/tested with). In the ESPHome add-on you can roll back the add-on version; with the CLI, `pip install 'esphome==2026.6.5'`.

I'm working on a proper 2026.7-compatible fix. Will update here when it lands.

**Comment by TimDowker** [comment]
Thank you - I look forward to the fix.

Great work BTW!

**Comment by Csontikka** [comment]
Fixed in **v0.5.3** — you can drop the 2026.6.x pin and update to v0.5.3 (or `main`) on ESPHome 2026.7.

Root cause: 2026.7 reworked the ESP-IDF build generation and stopped routing component options through `platformio.ini`, so the component's old way of pulling in the vendored `microlink` library (a generated `patch_cmake.py` registered via `extra_scripts`) silently stopped running — hence `microlink.h: No such file or directory`. It's now wired via ESPHome's official `add_idf_component()`, verified building clean on both 2026.6.5 and 2026.7.0.

Thanks for the clear report — it lined up with a build-system change I was already chasing. Closing; reopen if it still doesn't build for you on v0.5.3.

**Comment by TimDowker** [comment]
Confirmed.  Everything is working now - thank you.
